### ISSUE TITLE
decode错误：eof

### ISSUE THREAD

**Issue by LDawns** [Zhang-Xiaoda/NJU-DisSys-2017#4]
在执行rf.peers[sever].Call(xx,xx)后系统返回了一个错误说

2021/11/23 19:00:21 ClientEnd.Call(): decode reply: EOF

查了很久也不明白是为什么

**Comment by LDawns** [comment]
兄弟们，RPC传递的结构体里面的变量命名一定要是大写字母开头啊，太怪了

**Comment by Air111** [comment]
6
